# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
  downtime_helper.class: AppBundle\Helper\Downtime\DowntimeHelper


services:
    # default configuration for services in *this* file
#    _defaults:
#        autowire: true
#        autoconfigure: true
#        public: false
#
##    # makes classes in src/AppBundle available to be used as services
#    AppBundle\:
#        resource: '../../src/AppBundle/*'
#        exclude: '../../src/AppBundle/{Entity,Repository}'
    _defaults: { public: true }
    app.notepad:
        class: AppBundle\Services\NotepadService
        arguments:
            - App\Entity\Notepad
            - App\Entity\NotepadsAlarms



    app.user_provider:
        class: AppBundle\Entity\User\UserProvider
        arguments: ["@session", '%lavoisierurl%',"@service_container"]
    downtime_helper:
        class:  AppBundle\Helper\Downtime\DowntimeHelper
    opCurl:
        class: AppBundle\Services\op\Curl
#        public: true
    urlCheck:
        class: AppBundle\Services\op\UrlCheck
    downtime.email:
        class: AppBundle\Services\Downtime\EmailService
        arguments: ["@doctrine.orm.entity_manager","@service_container"]
    opConfigFile:
        class: AppBundle\Services\op\ConfigFile

    #swiftmailer
    swiftmailer.transport.simplemailinvoker:
        class: Swift_Transport_SimpleMailInvoker

    swiftmailer.transport.eventdispatcher:
        class: Swift_Events_SimpleEventDispatcher

    swiftmailer.transport.real:
        class: Swift_Transport_MailTransport
        arguments: ["@swiftmailer.transport.simplemailinvoker", "@swiftmailer.transport.eventdispatcher"]

    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }
    id_store:
        class: AppBundle\Store\IdStore
        arguments:
            - "@=service('doctrine').getManager()"
            - "@lightsaml.system.time_provider"

    user_creator:
          class: AppBundle\Security\User\UserCreator
          arguments:
                - "@=service('doctrine').getManager()"
                - "@lightsaml_sp.username_mapper.simple"
#                - "@my_attributes_mapper"

    my_attributes_mapper:
          class: AppBundle\Entity\User\MyAttributeMapper

  #authentication failure event listener
    app.security.authentication_failure_event_listener:
        class: AppBundle\Listener\AuthenticationListener
        arguments: ["@service_container"]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onAuthenticationFailure }

    app.security.access_denied_handler:
        class: AppBundle\Security\AccessDeniedHandler
        public: false
        arguments: ["@templating","@router","@session"]