step:
  Author:
    id: Author
    value: +C.user+
  Modifier:
    id: Modifier
    value: +C.user+
  AuthorEmail:
    id: AuthorEmail
    value: +C.manager_email+
  Involve:
    id: Involve
    value: +C.manager_email+
  Priority:
    id: Priority
    value: less urgent
  Subject:
    id: Subject
    value: |
            [Dashboard] Issues detected at +C.site_name+
    required: true
    order: '10'
    quick: true
  NotificationStrategy:
    id: NotificationStrategy
    value: Every Change
  Description:
    id: Description
    order: 20
    label: Problem description
    value: |
     Dear site administrator,

     We have detected +C.pb_number+ problem(s) at +C.site_name+.
     Please find below a list of attached problems :

     +C.group+

     Reach ticket on dashboard :
     +C.ticket_link+

     Could you please have a look ?
     Thank you
     +C.user+
  Status:
    id: Status
    value: new
  Step:
    id: Step
    value: new
  Community:
    id: Community
    value: ROD